import { book, saveBookLocalStorage, removeFromBookList, isBookEmpty, updateBookList } from "../data/book.js"; 
import { addedMessage, editedMessage, deletedMessage } from "./controls/toast.js";

class Book{
    constructor(id, title, author, isbn){    
        this.id = id;    
        this.title = title;    
        this.author = author;    
        this.isbn = isbn;    
    }
}

class UI{
    static renderDisplayBooks(){
        let bookItemsHTML = '';
        const tbody = document.querySelector('.book-items');

        book.forEach((bookItem) => {
            const {id, title, author, isbn} = bookItem;

            if(!title && !author && !isbn) return;

            bookItemsHTML += 
            `
            <tr class="row-${id}" data-book-id="${id}">
                <td>${id}</td>
                <td>${title}</td>
                <td>${author}</td>
                <td>${isbn}</td>
                <td>
                    <div class="action-btn">
                        <button class="edit-btn js-edit-btn"
                        data-book-id="${id}">
                            Edit
                        </button>
                        <button class="delete-btn js-delete-btn"
                        data-book-id="${id}">
                            Delete
                        </button>
                    </div>
                </td>
            </tr>
            `;
            tbody.innerHTML = bookItemsHTML;
        });
    }

    static addBookToList(){
        let autoGeneratedId = book.length === 0 ? 1 : Math.max(...book.map(b => b.id)) + 1;

        const titleInput = document.querySelector('#title');
        const authorInput = document.querySelector('#author');
        const isbnInput = document.querySelector('#isbn');

        const title = titleInput.value;
        const author = authorInput.value;
        const isbn = isbnInput.value;

        // Validation
        if(!title || !author || !isbn){
            console.log('Please fill up the fields');
            return;
        }

        const newBook = new Book(autoGeneratedId, title, author, isbn);

        book.push(newBook);
        saveBookLocalStorage();
        isBookEmpty();
        UI.renderDisplayBooks();
        addedMessage();

        autoGeneratedId++;

        // CLEAR INPUTS (FIXED)
        titleInput.value = '';
        authorInput.value = '';
        isbnInput.value = '';
    }

    static deleteBookList(id) {
        removeFromBookList(id);
        const tableRow = document.querySelector(`.row-${id}`);

        if(tableRow) tableRow.remove();
    }

    static saveEditBook(){
        const addBookButton = document.querySelector('.js-save');
            addBookButton.addEventListener('click', (e) =>{
                // Kasi nasa form ang button
                e.preventDefault();
                
                const bookId =  Number(e.target.dataset.bookId);

                const newTitleInput = document.querySelector('#title-modal');
                const newAuthorInput = document.querySelector('#author-modal');
                const newIsbnInput = document.querySelector('#isbn-modal');

                const newTitle = newTitleInput.value;
                const newAuthor = newAuthorInput.value;
                const newIsbn = newIsbnInput.value;

                UI.closeEditModal();
                updateBookList(bookId, newTitle, newAuthor, newIsbn);
                UI.renderDisplayBooks();
                editedMessage();
            });
    }

    static openEditModal(id){
        const bookItem = book.find(item => item.id === id);
        const innderModalHTML = 
        `
        <div class="inner-modal">
            <h2>Editing Book</h2>
            <form id="my-from" class="my-form-modal">
                <div class="form-group-modal">
                    <label for="title" >Title:</label>
                    <input type="text" id="title-modal" class="js-title" value="${bookItem.title}">
                </div>
                <div class="form-group-modal">
                    <label for="author" >Author:</label>
                    <input type="text" id="author-modal"  class="js-author" value="${bookItem.author}">
                </div>
                <div class="form-group-modal">
                    <label for="isbn" >ISBN:</label>
                    <input type="text" id="isbn-modal"  class="js-isbn" value="${bookItem.isbn}">
                </div>
                <button class="save-book-btn js-save" data-book-id="${id}">Save</button>
            </form>
        </div>
        `;
        document.querySelector('.edit-modal').innerHTML = innderModalHTML;

        const bodyContainer = document.querySelector('.container-body');
        bodyContainer.classList.add('opacity-body');
        const modalContainer = document.querySelector('.edit-modal');
        modalContainer.classList.add('show-modal');
    }

    static closeEditModal(){
        const bodyContainer = document.querySelector('.container-body');
        bodyContainer.classList.remove('opacity-body');
        const modalContainer = document.querySelector('.edit-modal');
        modalContainer.classList.remove('show-modal');
    }


}


const addBookButton = document.querySelector('.js-add');
addBookButton.addEventListener('click', (e) =>{
    // Kasi nasa form ang button
    e.preventDefault();
    UI.addBookToList();
});


// Event Delegation // Delete
// Imbes na maglagay ng event listener sa bawat button, isang listener lang ang 
// nilalagay sa parent element, tapos chine-check kung anong child element 
// ang na-click.
document.querySelector('.book-items')
.addEventListener('click', (e) => {
    if(e.target.classList.contains('js-delete-btn')){
        const bookId = Number(e.target.dataset.bookId);
        
        UI.deleteBookList(bookId);
        deletedMessage();
        isBookEmpty();
        UI.renderDisplayBooks();
        console.log(book);
    }
});


// Edit
document.querySelector('.book-items')
.addEventListener('click', (e) => {
    if(e.target.classList.contains('js-edit-btn')){
        const bookId = Number(e.target.dataset.bookId);
        
        UI.openEditModal(bookId);
        UI.saveEditBook();
        console.log('edit');
    }
});




console.log(book);
isBookEmpty();
UI.renderDisplayBooks();